[project]
name = "multimodaltaxonomy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.4.0",
    "qwen-vl-utils>=0.0.11",
]
